### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by scarletocean** [salesforce/DiverseSumm#4]
Hi! Thank you so smuch for your efforts, when will the code be released? Really looking forward to it!

**Comment by yilihsu** [comment]
same here!

**Comment by khuangaf** [comment]
Hi, thank you for your interest in our work! We have released our summary generation code in the [scripts](https://github.com/salesforce/DiverseSumm/tree/main/scripts) folder. Please let us know if you have any further questions!

**Comment by yilihsu** [comment]
Hi! Thank you for releasing the code for summary generation. Could you also share the code that includes the full pipeline described in the paper, such as QA generation and clustering?

**Comment by khuangaf** [comment]
Hi @yilihsu, sure, we just released them [here](https://github.com/salesforce/DiverseSumm/tree/main/scripts/data_gen)! They are based on the [Discord Questions](https://github.com/salesforce/discord_questions) framework. Feel free to reach out if you have questions.
